# Question 1

In [60]:
List=[]
for i in range(2000,3201): 
     if i%7==0 and i%5!=0:
            List.append(i)
            
print(List)            

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# Question 2

In [82]:
#Question 2
def fact(x):
    facto=1
    if x==0:
        return 1
    else:
        for i in range (1,x+1):
            facto=facto*i
            
        return facto           
        
number=input("Give a number: ")  
print(fact(int(number)))

Give a number: -9
1


# Question3

In [102]:
number=input("Give a number: ")
Dict={}
for i in range(1,int(number)+1):
    Dict[i]=int(i*i)
print(Dict)    

Give a number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# Question 4

In [103]:
ch=input("Give a non-empty string: ")
number=input("Give a number less than the word length: ")
while int(number)<0 or int(number)>len(ch):
    number=input("Give a number less than the word length: ")
ch=ch[:int(number)]+ch[int(number)+1:]
print("The new word: ",ch)

Give a non-empty string: Hello
Give a number less than the word length: 2
The new word:  Helo


# Question 5

In [130]:
import numpy as np
array=np.array([[0,1],[2,3]])
L=array.tolist()
print(L)

[[0, 1], [2, 3]]


# Question 6

In [118]:
import numpy as np
array1=np.array([0,1,2])
array2=np.array([2,1,0])
print(array1)
print(array2)
np.cov(array1,array2)


[0 1 2]
[2 1 0]


array([[ 1., -1.],
       [-1.,  1.]])

# Question 7

In [169]:
import math
C=50
H=30
list=[]
def calculate(D):
    return math.trunc(math.sqrt((2*C*D)/H))
L = [int(x) for x in input("Enter multiple values\n").split(', ')] 
print("\nThe list", L)  
for i in range(len(L)):
    list.append(str(calculate(L[i])))
ch=",".join(list)    
print(ch)    

Enter multiple values
100, 150, 180

The list [100, 150, 180]
18,22,24
